component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/proguard/.*
- ./bin/proguard/annotation/.*
- ./bin/proguard/ant/.*
- ./bin/proguard/classfile/.*
- ./bin/proguard/classfile/attribute/.*
- ./bin/proguard/classfile/attribute/annotation/.*
- ./bin/proguard/classfile/attribute/annotation/visitor/.*
- ./bin/proguard/classfile/attribute/preverification/.*
- ./bin/proguard/classfile/attribute/preverification/visitor/.*
- ./bin/proguard/classfile/attribute/visitor/.*
- ./bin/proguard/classfile/constant/.*
- ./bin/proguard/classfile/constant/visitor/.*
- ./bin/proguard/classfile/editor/.*
- ./bin/proguard/classfile/instruction/.*
- ./bin/proguard/classfile/instruction/visitor/.*
- ./bin/proguard/classfile/io/.*
- ./bin/proguard/classfile/util/.*
- ./bin/proguard/classfile/visitor/.*
- ./bin/proguard/evaluation/.*
- ./bin/proguard/evaluation/value/.*
- ./bin/proguard/gradle/.*
- ./bin/proguard/gui/.*
- ./bin/proguard/gui/splash/.*
- ./bin/proguard/io/.*
- ./bin/proguard/obfuscate/.*
- ./bin/proguard/optimize/.*
- ./bin/proguard/optimize/evaluation/.*
- ./bin/proguard/optimize/info/.*
- ./bin/proguard/optimize/peephole/.*
- ./bin/proguard/preverify/.*
- ./bin/proguard/retrace/.*
- ./bin/proguard/shrink/.*
- ./bin/proguard/util/.*
- ./bin/proguard/wtk/.*
- ./build/.*
- ./build/maven/.*
- ./build/maven/ant/.*
- ./build/maven/base/.*
- ./build/maven/gradle/.*
- ./build/maven/gui/.*
- ./build/maven/retrace/.*
- ./build/maven/wtk/.*
- ./docs/.*
- ./docs/manual/.*
- ./docs/manual/retrace/.*
- ./examples/.*
- ./examples/annotations/.*
- ./examples/annotations/examples/.*
- ./examples/annotations/lib/.*
- ./examples/ant/.*
- ./examples/dictionaries/.*
- ./examples/gradle/.*
- ./lib/.*
